# Generated by Django 5.0.7 on 2024-07-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TestItemTypeDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TestDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjectdatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='TestItemDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=128)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testdatamodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testitemtypedatamodel')),
            ],
        ),
    ]
