# Generated by Django 5.0.7 on 2024-07-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subjectdatamodel',
            table='subject',
        ),
        migrations.AlterModelTable(
            name='testdatamodel',
            table='test',
        ),
        migrations.AlterModelTable(
            name='testitemdatamodel',
            table='test_item',
        ),
        migrations.AlterModelTable(
            name='testitemtypedatamodel',
            table='test_item_type',
        ),
    ]
