# Generated by Django 5.0.7 on 2024-07-11 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subjectdatamodel_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestItemOptionDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=64)),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testitemdatamodel')),
            ],
            options={
                'db_table': 'test_item_option',
            },
        ),
        migrations.CreateModel(
            name='TestItemAnswerDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testitemdatamodel')),
                ('test_item_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testitemoptiondatamodel')),
            ],
            options={
                'db_table': 'test_item_answer',
            },
        ),
        migrations.CreateModel(
            name='UserResultDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField(default=False)),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testitemdatamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
