# Generated by Django 5.0.7 on 2024-07-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testitemoptiondatamodel_testitemanswerdatamodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userresultdatamodel',
            table='user_result',
        ),
    ]
