# Generated by Django 5.0.7 on 2024-08-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userresultdatamodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectdatamodel',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='testdatamodel',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='testitemanswerdatamodel',
            options={'verbose_name': 'Test item answer', 'verbose_name_plural': 'Test item answers'},
        ),
        migrations.AlterModelOptions(
            name='testitemdatamodel',
            options={'verbose_name': 'Test item', 'verbose_name_plural': 'Test items'},
        ),
        migrations.AlterModelOptions(
            name='testitemoptiondatamodel',
            options={'verbose_name': 'Test item option', 'verbose_name_plural': 'Test item options'},
        ),
        migrations.AlterModelOptions(
            name='testitemtypedatamodel',
            options={'verbose_name': 'Test item type', 'verbose_name_plural': 'Test item types'},
        ),
        migrations.AlterModelOptions(
            name='userresultdatamodel',
            options={'verbose_name': 'User result', 'verbose_name_plural': 'User results'},
        ),
        migrations.AddField(
            model_name='testitemdatamodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testdatamodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.subjectdatamodel'),
        ),
    ]
