# Generated by Django 5.0.7 on 2024-08-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subjectdatamodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitemdatamodel',
            name='question',
            field=models.CharField(max_length=256),
        ),
    ]
